from . import medical_policy
from . import policy_category
from . import insurance_for
from . import risks
from . import policy_cover_line
from . import policy_management_dashboard
from . import medical_risks
from . import life_policy
from . import life_risks
from . import motor_policy
from . import fire_policy
from . import engineering_policy
from . import misc_policy
from . import marine_policy
from . import motor_risks
from . import fire_risks
from . import misc_risks
from . import engineering_risks
from . import marine_risks
from . import cover_risks_line
from . import policy_product
from . import risks_line